FROM php:7.3-apache

# Install required libs
RUN apt-get update && \
    apt-get install -y \
        libpng-dev \
        libmcrypt-dev \
    && apt-get clean

#
# Install extensions
#
RUN docker-php-ext-install \
    ctype \
    mbstring \
    pdo_mysql \
    bcmath \
    gd \
    && a2enmod \
    rewrite

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf